### PR TITLE
Order List API - Order Management Page

### PR DESCRIPTION
**Pull request by rjbelleza**
### Description
- This PR intends to enhance the Order Management page by serving requests coming from the system's frontend. It allows the fetching of all the list of orders from the database and send it as response to the frontend's requests.

### Features created/files changed
- Created a `showAll` function in the `OrderController` to fetch all order details from the database.
- Created the logic for order fetching, connected tables.
- Created a route for the order fetch request.

### CODE REVIEW

**Review by Stephen-cpu-ui — APPROVED** [review]

**Comment by philipelbambo** [comment]
Approved 👍

**Comment by philipelbambo** [comment]
Approved 👍

**Comment by Skenkenken** [comment]
Nice implementation🙌

**Comment by Skenkenken** [comment]
Nice implementation🙌

**Pull request merged**
